$data.Entity.extend("Properties", {
    ListingKey: { type: "string", maxLength: 255 },
    ListingId: { type: "int", key: true, computed: false},
    ListAOR: { type: "string", maxLength: 50 },
    OriginatingSystemKey: { type: "string", maxLength: 255 },
    OriginatingSystemName: { type: "string", maxLength: 255 },
    ListingService: { type: "string", maxLength: 25 },
    ListingAgreement: { type: "string", maxLength: 25 },
    LeaseConsideredYN: { type: "boolean" },
    HomeWarrantyYN: { type: "boolean" },
    CopyrightNotice: { type: "string", maxLength: 500 },
    Disclaimer: { type: "string", maxLength: 500 },
    StandardStatus: { type: "string", maxLength: 25 },
    MlsStatus: { type: "string", maxLength: 50 },
    ApprovalStatus: { type: "string", maxLength: 25 },
    ListingContractDate: { type: "date" },
    ContractStatusChangeDate: { type: "date" },
    ExpirationDate: { type: "date" },
    CancelationDate: { type: "date" },
    ContingentDate: { type: "date" },
    WithdrawnDate: { type: "date" },
    PurchaseContractDate: { type: "date" },
    CloseDate: { type: "date" },
    OnMarketDate: { type: "date" },
    OffMarketDate: { type: "date" },
    PendingTimestamp: { type: "datetime" },
    ModificationTimestamp: { type: "datetime" },
    StatusChangeTimestamp: { type: "datetime" },
    PriceChangeTimestamp: { type: "datetime" },
    MajorChangeType: { type: "string", maxLength: 255 },
    MajorChangeTimestamp: { type: "datetime" },
    OriginalEntryTimestamp: { type: "datetime" },
    OnMarketTimestamp: { type: "datetime" },
    OffMarketTimestamp: { type: "datetime" },
    DaysOnMarket: { type: "int" },
    CumulativeDaysOnMarket: { type: "int" },
    ClosePrice: { type: "number" },
    ListPrice: { type: "number", required: true },
    OriginalListPrice: { type: "number" },
    ListPriceLow: { type: "number" },
    PreviousListPrice: { type: "number" },
    BuyerAgencyCompensation: { type: "string", maxLength: 25 },
    BuyerAgencyCompensationType: { type: "string", maxLength: 25 },
    SubAgencyCompensation: { type: "string", maxLength: 25 },
    SubAgencyCompensationType: { type: "string", maxLength: 25 },
    TransactionBrokerCompensation: { type: "string", maxLength: 25 },
    TransactionBrokerCompensationType: { type: "string", maxLength: 25 },
    DualVariableCompensationYN: { type: "boolean" },
    LeaseRenewalCompensation: { type: "string", maxLength: 255 },
    VOWEntireListingDisplayYN: { type: "boolean" },
    VOWAddressDisplayYN: { type: "boolean" },
    VOWConsumerCommentYN: { type: "boolean" },
    VOWAutomatedValuationDisplayYN: { type: "boolean" },
    SignOnPropertyYN: { type: "boolean" },
    IDXEntireListingDisplayYN: { type: "boolean" },
    IDXAddressDisplayYN: { type: "boolean" },
    IDXConsumerCommentYN: { type: "boolean" },
    IDXAutomatedValuationDisplayYN: { type: "boolean" },
    PhotosCount: { type: "int" },
    PhotosChangeTimestamp: { type: "datetime" },
    VideosCount: { type: "int" },
    VideosChangeTimestamp: { type: "datetime" },
    DocumentsCount: { type: "int" },
    DocumentsChangeTimestamp: { type: "datetime" },
    DocumentsAvailable: { type: "string", maxLength: 1024 },
    VirtualTourURLUnbranded: { type: "string", maxLength: 8000 },
    VirtualTourURLBranded: { type: "string", maxLength: 8000 },
    PublicRemarks: { type: "string", maxLength: 4000 },
    PrivateRemarks: { type: "string", maxLength: 4000 },
    PrivateOfficeRemarks: { type: "string", maxLength: 4000 },
    ShowingInstructions: { type: "string", maxLength: 4000 },
    ShowingContactPhoneNumber: { type: "string", maxLength: 16 },
    ShowingContactPhoneExtension: { type: "int" },
    ShowingContactName: { type: "string", maxLength: 40 },
    ShowingContactType: { type: "string", maxLength: 75 },
    LockBoxLocation: { type: "string", maxLength: 255 },
    LockBoxType: { type: "string", maxLength: 255 },
    LockBoxSerialNumber: { type: "string", maxLength: 25 },
    Exclusions: { type: "string", maxLength: 1024 },
    Inclusions: { type: "string", maxLength: 1024 },
    Disclosures: { type: "string", maxLength: 4000 },
    Ownership: { type: "string", maxLength: 1024 },
    SpecialListingConditions: { type: "string", maxLength: 1024 },
    ListingTerms: { type: "string", maxLength: 1024 },
    ListingFinancing: { type: "string", maxLength: 1024 },
    BuyerFinancing: { type: "string", maxLength: 1024 },
    Contingency: { type: "string", maxLength: 1024 },
    Possession: { type: "string", maxLength: 255 },
    ClosingTerms: { type: "string", maxLength: 1024 },
    StreetNumber: { type: "string", required: true, maxLength: 25 },
    StreetNumberNumeric: { type: "int" },
    StreetDirPrefix: { type: "string", maxLength: 15 },
    StreetName: { type: "string", required: true, maxLength: 50 },
    StreetAdditionalInfo: { type: "string", maxLength: 50 },
    StreetSuffix: { type: "string", maxLength: 25 },
    StreetSuffixModifier: { type: "string", maxLength: 25 },
    StreetDirSuffix: { type: "string", maxLength: 15 },
    UnitNumber: { type: "string", maxLength: 25 },
    City: { type: "string", required: true, maxLength: 50 },
    StateOrProvince: { type: "string", required: true, maxLength: 2 },
    Country: { type: "string", maxLength: 2 },
    PostalCode: { type: "string", required: true, maxLength: 10 },
    PostalCodePlus4: { type: "string", maxLength: 4 },
    CarrierRoute: { type: "string", maxLength: 9 },
    UnparsedAddress: { type: "string", maxLength: 255 },
    PostalCity: { type: "string", maxLength: 50 },
    CountyOrParish: { type: "string", maxLength: 50 },
    Township: { type: "string", maxLength: 50 },
    MLSAreaMajor: { type: "string", maxLength: 50 },
    MLSAreaMinor: { type: "string", maxLength: 50 },
    SubdivisionName: { type: "string", maxLength: 50 },
    Latitude: { type: "number" },
    Longitude: { type: "number" },
    Directions: { type: "string", maxLength: 1024 },
    MapCoordinate: { type: "string", maxLength: 25 },
    MapCoordinateSource: { type: "string", maxLength: 25 },
    MapURL: { type: "string", maxLength: 8000 },
    CrossStreet: { type: "string", maxLength: 50 },
    ElementarySchool: { type: "string", maxLength: 50 },
    ElementarySchoolDistrict: { type: "string", maxLength: 50 },
    MiddleOrJuniorSchool: { type: "string", maxLength: 50 },
    MiddleOrJuniorSchoolDistrict: { type: "string", maxLength: 50 },
    HighSchool: { type: "string", maxLength: 50 },
    HighSchoolDistrict: { type: "string", maxLength: 50 },
    ListAgentNamePrefix: { type: "string", maxLength: 10 },
    ListAgentFirstName: { type: "string", required: true, maxLength: 50 },
    ListAgentMiddleName: { type: "string", maxLength: 50 },
    ListAgentLastName: { type: "string", required: true, maxLength: 50 },
    ListAgentNameSuffix: { type: "string", maxLength: 10 },
    ListAgentFullName: { type: "string", maxLength: 150 },
    ListAgentPreferredPhone: { type: "string", maxLength: 16 },
    ListAgentPreferredPhoneExt: { type: "int" },
    ListAgentOfficePhone: { type: "string", maxLength: 16 },
    ListAgentOfficePhoneExt: { type: "int" },
    ListAgentCellPhone: { type: "string", maxLength: 16 },
    ListAgentDirectPhone: { type: "string", maxLength: 16 },
    ListAgentHomePhone: { type: "string", maxLength: 16 },
    ListAgentFax: { type: "string", maxLength: 16 },
    ListAgentPager: { type: "string", maxLength: 16 },
    ListAgentVoiceMail: { type: "string", maxLength: 16 },
    ListAgentVoiceMailExt: { type: "int" },
    ListAgentTollFreePhone: { type: "string", maxLength: 16 },
    ListAgentEmail: { type: "string", required: true, maxLength: 80 },
    ListAgentURL: { type: "string", maxLength: 8000 },
    ListAgentKey: { type: "string", maxLength: 255 },
    ListAgentAOR: { type: "string", maxLength: 50 },
    ListAgentMlsId: { type: "int"},
    ListAgentStateLicense: { type: "string", maxLength: 50 },
    ListAgentDesignation: { type: "string", maxLength: 50 },
    ListOfficeName: { type: "string", required: true, maxLength: 50 },
    ListOfficePhone: { type: "string", maxLength: 16 },
    ListOfficePhoneExt: { type: "int" },
    ListOfficeFax: { type: "string", maxLength: 16 },
    ListOfficeEmail: { type: "string", maxLength: 80 },
    ListOfficeURL: { type: "string", maxLength: 8000 },
    ListOfficeKey: { type: "string", maxLength: 255 },
    ListOfficeAOR: { type: "string", maxLength: 50 },
    ListOfficeMlsId: { type: "string", maxLength: 25 },
    CoListAgentNamePrefix: { type: "string", maxLength: 10 },
    CoListAgentFirstName: { type: "string", maxLength: 50 },
    CoListAgentMiddleName: { type: "string", maxLength: 50 },
    CoListAgentLastName: { type: "string", maxLength: 50 },
    CoListAgentNameSuffix: { type: "string", maxLength: 10 },
    CoListAgentFullName: { type: "string", maxLength: 150 },
    CoListAgentPreferredPhone: { type: "string", maxLength: 16 },
    CoListAgentPreferredPhoneExt: { type: "int" },
    CoListAgentOfficePhone: { type: "string", maxLength: 16 },
    CoListAgentOfficePhoneExt: { type: "int" },
    CoListAgentCellPhone: { type: "string", maxLength: 16 },
    CoListAgentDirectPhone: { type: "string", maxLength: 16 },
    CoListAgentHomePhone: { type: "string", maxLength: 16 },
    CoListAgentFax: { type: "string", maxLength: 16 },
    CoListAgentPager: { type: "string", maxLength: 16 },
    CoListAgentVoiceMail: { type: "string", maxLength: 16 },
    CoListAgentVoiceMailExt: { type: "int" },
    CoListAgentTollFreePhone: { type: "string", maxLength: 16 },
    CoListAgentEmail: { type: "string", maxLength: 80 },
    CoListAgentURL: { type: "string", maxLength: 8000 },
    CoListAgentKey: { type: "string", maxLength: 255 },
    CoListAgentAOR: { type: "string", maxLength: 50 },
    CoListAgentMlsId: { type: "int"},
    CoListAgentStateLicense: { type: "string", maxLength: 50 },
    CoListAgentDesignation: { type: "string", maxLength: 50 },
    CoListOfficeName: { type: "string", maxLength: 50 },
    CoListOfficePhone: { type: "string", maxLength: 16 },
    CoListOfficePhoneExt: { type: "int" },
    CoListOfficeFax: { type: "string", maxLength: 16 },
    CoListOfficeEmail: { type: "string", maxLength: 80 },
    CoListOfficeURL: { type: "string", maxLength: 8000 },
    CoListOfficeKey: { type: "string", maxLength: 255 },
    CoListOfficeAOR: { type: "string", maxLength: 50 },
    CoListOfficeMlsId: { type: "string", maxLength: 25 },
    BuyerAgentNamePrefix: { type: "string", maxLength: 10 },
    BuyerAgentFirstName: { type: "string", maxLength: 50 },
    BuyerAgentMiddleName: { type: "string", maxLength: 50 },
    BuyerAgentLastName: { type: "string", maxLength: 50 },
    BuyerAgentNameSuffix: { type: "string", maxLength: 10 },
    BuyerAgentFullName: { type: "string", maxLength: 150 },
    BuyerAgentPreferredPhone: { type: "string", maxLength: 16 },
    BuyerAgentPreferredPhoneExt: { type: "int" },
    BuyerAgentOfficePhone: { type: "string", maxLength: 16 },
    BuyerAgentOfficePhoneExt: { type: "int" },
    BuyerAgentCellPhone: { type: "string", maxLength: 16 },
    BuyerAgentDirectPhone: { type: "string", maxLength: 16 },
    BuyerAgentHomePhone: { type: "string", maxLength: 16 },
    BuyerAgentFax: { type: "string", maxLength: 16 },
    BuyerAgentPager: { type: "string", maxLength: 16 },
    BuyerAgentVoiceMail: { type: "string", maxLength: 16 },
    BuyerAgentVoiceMailExt: { type: "int" },
    BuyerAgentTollFreePhone: { type: "string", maxLength: 16 },
    BuyerAgentEmail: { type: "string", maxLength: 80 },
    BuyerAgentURL: { type: "string", maxLength: 8000 },
    BuyerAgentKey: { type: "string", maxLength: 255 },
    BuyerAgentAOR: { type: "string", maxLength: 50 },
    BuyerAgentMlsId: { type: "string", maxLength: 25 },
    BuyerAgentStateLicense: { type: "string", maxLength: 50 },
    BuyerAgentDesignation: { type: "string", maxLength: 50 },
    BuyerOfficeName: { type: "string", maxLength: 50 },
    BuyerOfficePhone: { type: "string", maxLength: 16 },
    BuyerOfficePhoneExt: { type: "int" },
    BuyerOfficeFax: { type: "string", maxLength: 16 },
    BuyerOfficeEmail: { type: "string", maxLength: 80 },
    BuyerOfficeURL: { type: "string", maxLength: 8000 },
    BuyerOfficeKey: { type: "string", maxLength: 255 },
    BuyerOfficeAOR: { type: "string", maxLength: 50 },
    BuyerOfficeMlsId: { type: "string", maxLength: 25 },
    CoBuyerAgentNamePrefix: { type: "string", maxLength: 10 },
    CoBuyerAgentFirstName: { type: "string", maxLength: 50 },
    CoBuyerAgentMiddleName: { type: "string", maxLength: 50 },
    CoBuyerAgentLastName: { type: "string", maxLength: 50 },
    CoBuyerAgentNameSuffix: { type: "string", maxLength: 10 },
    CoBuyerAgentFullName: { type: "string", maxLength: 150 },
    CoBuyerAgentPreferredPhone: { type: "string", maxLength: 16 },
    CoBuyerAgentPreferredPhoneExt: { type: "int" },
    CoBuyerAgentOfficePhone: { type: "string", maxLength: 16 },
    CoBuyerAgentOfficePhoneExt: { type: "int" },
    CoBuyerAgentCellPhone: { type: "string", maxLength: 16 },
    CoBuyerAgentDirectPhone: { type: "string", maxLength: 16 },
    CoBuyerAgentHomePhone: { type: "string", maxLength: 16 },
    CoBuyerAgentFax: { type: "string", maxLength: 16 },
    CoBuyerAgentPager: { type: "string", maxLength: 16 },
    CoBuyerAgentVoiceMail: { type: "string", maxLength: 16 },
    CoBuyerAgentVoiceMailExt: { type: "int" },
    CoBuyerAgentTollFreePhone: { type: "string", maxLength: 16 },
    CoBuyerAgentEmail: { type: "string", maxLength: 80 },
    CoBuyerAgentURL: { type: "string", maxLength: 8000 },
    CoBuyerAgentKey: { type: "string", maxLength: 255 },
    CoBuyerAgentAOR: { type: "string", maxLength: 50 },
    CoBuyerAgentMlsId: { type: "string", maxLength: 25 },
    CoBuyerAgentStateLicense: { type: "string", maxLength: 50 },
    CoBuyerAgentDesignation: { type: "string", maxLength: 50 },
    CoBuyerOfficeName: { type: "string", maxLength: 50 },
    CoBuyerOfficePhone: { type: "string", maxLength: 16 },
    CoBuyerOfficePhoneExt: { type: "int" },
    CoBuyerOfficeFax: { type: "string", maxLength: 16 },
    CoBuyerOfficeEmail: { type: "string", maxLength: 80 },
    CoBuyerOfficeURL: { type: "string", maxLength: 8000 },
    CoBuyerOfficeKey: { type: "string", maxLength: 255 },
    CoBuyerOfficeAOR: { type: "string", maxLength: 50 },
    CoBuyerOfficeMlsId: { type: "string", maxLength: 25 },

    ListTeamDisplayName: { type: "string", maxLength: 50 },
    BuyerTeamDisplayName: { type: "string", maxLength: 50 },
    PropertyType: { type: "string", maxLength: 50 },
    PropertySubType: { type: "string", maxLength: 50 },
    AssociationYN: { type: "boolean" },
    AssociationName: { type: "string", maxLength: 50 },
    AssociationPhone: { type: "string", maxLength: 16 },
    AssociationFee: { type: "number" },
    AssociationFeeFrequency: { type: "string", maxLength: 25 },
    AssociationName2: { type: "string", maxLength: 50 },
    AssociationPhone2: { type: "string", maxLength: 16 },
    AssociationFee2: { type: "number" },
    AssociationFee2Frequency: { type: "string", maxLength: 25 },
    AssociationFeeIncludes: { type: "string", maxLength: 1024 },
    AssociationAmenities: { type: "string", maxLength: 1024 },
    LotSizeArea: { type: "number" },
    LotSizeSource: { type: "string", maxLength: 50 },
    LotSizeUnits: { type: "string", maxLength: 25 },
    LotSizeDimensions: { type: "string", maxLength: 150 },
    LotDimensionsSource: { type: "string", maxLength: 50 },
    LotSizeAcres: { type: "number" },
    LotSizeSquareFeet: { type: "number" },
    FrontageType: { type: "string", maxLength: 50 },
    FrontageLength: { type: "string", maxLength: 255 },
    RoadFrontageType: { type: "string", maxLength: 255 },
    RoadSurfaceType: { type: "string", maxLength: 255 },
    RoadResponsibility: { type: "string", maxLength: 50 },
    OccupantName: { type: "string", maxLength: 50 },
    OccupantPhone: { type: "string", maxLength: 16 },
    OccupantType: { type: "string", maxLength: 50 },
    OwnerName: { type: "string", maxLength: 50 },
    OwnerPhone: { type: "string", maxLength: 16 },
    LeaseTerm: { type: "string", maxLength: 25 },
    LandLeaseYN: { type: "boolean" },
    LandLeaseAmount: { type: "number" },
    LandLeaseAmountFrequency: { type: "string", maxLength: 25 },
    LandLeaseExpirationDate: { type: "date" },
    View: { type: "string", maxLength: 1024 },
    ViewYN: { type: "boolean" },
    LotFeatures: { type: "string", maxLength: 1024 },
    CurrentUse: { type: "string", maxLength: 1024 },
    PossibleUse: { type: "string", maxLength: 1024 },
    DevelopmentStatus: { type: "string", maxLength: 1024 },
    NumberofLots: { type: "int" },
    HorseYN: { type: "boolean" },
    HorseAmenities: { type: "string", maxLength: 1024 },
    CommunityFeatures: { type: "string", maxLength: 1024 },
    SeniorCommunityYN: { type: "boolean" },
    PoolFeatures: { type: "string", maxLength: 1024 },
    PoolPrivateYN: { type: "boolean" },
    SpaFeatures: { type: "string", maxLength: 1024 },
    SpaYN: { type: "boolean" },
    WaterfrontYN: { type: "boolean" },
    WaterBodyName: { type: "string", maxLength: 50 },
    GrossScheduledIncome: { type: "number" },
    IncomeIncludes: { type: "string", maxLength: 1024 },
    OperatingExpense: { type: "number" },
    OperatingExpenseIncludes: { type: "string", maxLength: 1024 },
    NetOperatingIncome: { type: "number" },
    CapRate: { type: "number" },
    NumberOfUnitsLeased: { type: "int" },
    NumberOfUnitsMoMo: { type: "int" },
    NumberOfUnitsVacant: { type: "int" },
    ExistingLeaseType: { type: "string", maxLength: 75 },
    UnitsFurnished: { type: "string", maxLength: 25 },
    TotalActualRent: { type: "number" },
    RentControlYN: { type: "boolean" },
    NumberOfUnitsTotal: { type: "int" },
    NumberOfUnitsBuildings: { type: "int" },
    TenantPays: { type: "string", maxLength: 255 },
    OwnerPays: { type: "string", maxLength: 255 },
    VacancyAllowance: { type: "int" },
    CableTvExpense: { type: "number" },
    ElectricExpense: { type: "number" },
    GardnerExpense: { type: "number" },
    FurnitureReplacementExpense: { type: "number" },
    GasExpense: { type: "number" },
    InsuranceExpense: { type: "number" },
    OtherExpense: { type: "number" },
    LicensesExpense: { type: "number" },
    NewTaxesExpense: { type: "number" },
    MaintenanceExpense: { type: "string" },
    PestControlExpense: { type: "number" },
    WaterSewerExpense: { type: "number" },
    PoolExpense: { type: "number" },
    SuppliesExpense: { type: "number" },
    TrashExpense: { type: "number" },
    WorkmansCompensationExpense: { type: "number" },
    ProfessionalManagementExpense: { type: "number" },
    ManagerExpense: { type: "number" },
    FinancialDataSource: { type: "string", maxLength: 75 },
    RentIncludes: { type: "string", maxLength: 255 },
    Utilities: { type: "string", maxLength: 1024 },
    Electric: { type: "string", maxLength: 255 },
    Gas: { type: "string", maxLength: 255 },
    Telephone: { type: "string", maxLength: 255 },
    IrrigationWaterRightsYN: { type: "boolean" },
    IrrigationWaterRightsAcres: { type: "int" },
    IrrigationSource: { type: "string", maxLength: 255 },
    WaterSource: { type: "string", maxLength: 1024 },
    DistanceToWater: { type: "string", maxLength: 255 },
    ElectricOnPropertyYN: { type: "string", maxLength: 1 },
    DistanceToElectric: { type: "string", maxLength: 255 },
    Sewer: { type: "string", maxLength: 1024 },
    DistanceToSewer: { type: "string", maxLength: 255 },
    DistanceToGas: { type: "string", maxLength: 255 },
    DistanceToPhoneService: { type: "string", maxLength: 255 },
    DistanceToStreet: { type: "string", maxLength: 255 },
    DistanceToSchools: { type: "string", maxLength: 255 },
    DistanceFromShopping: { type: "string", maxLength: 255 },
    DistanceToPlaceofWorship: { type: "string", maxLength: 255 },
    DistanceToBus: { type: "string", maxLength: 255 },
    DistanceToFreeway: { type: "string", maxLength: 255 },
    CropsIncludedYN: { type: "boolean" },
    GrazingPermitsBlmYN: { type: "boolean" },
    GrazingPermitsForestServiceYN: { type: "boolean" },
    GrazingPermitsPrivateYN: { type: "boolean" },
    CultivatedArea: { type: "number" },
    PastureArea: { type: "number" },
    RangeArea: { type: "number" },
    WoodedArea: { type: "number" },
    Vegetation: { type: "string", maxLength: 1024 },
    Fencing: { type: "string", maxLength: 255 },
    DistanceFromSchoolBus: { type: "string", maxLength: 255 },
    FarmCreditServiceInclYN: { type: "boolean" },
    FarmLandAreaUnits: { type: "string", maxLength: 25 },
    FarmLandAreaSource: { type: "string", maxLength: 50 },
    BedroomsTotal: { type: "int", required: true },
    BedroomsPossible: { type: "int" },
    BathroomsTotal: { type: "string", required: true, maxLength: 25 },
    BathroomsFull: { type: "int" },
    BathroomsHalf: { type: "int" },
    BathroomsThreeQuarter: { type: "int" },
    BathroomsOneQuarter: { type: "int" },
    LivingArea: { type: "number", required: true },
    LivingAreaSource: { type: "string", maxLength: 50 },
    LivingAreaUnits: { type: "string", maxLength: 25 },
    AboveGradeFinishedArea: { type: "number" },
    AboveGradeFinishedAreaSource: { type: "string", maxLength: 50 },
    AboveGradeFinishedAreaUnits: { type: "string", maxLength: 25 },
    BelowGradeFinishedArea: { type: "number" },
    BelowGradeFinishedAreaSource: { type: "string", maxLength: 50 },
    BelowGradeFinishedAreaUnits: { type: "string", maxLength: 25 },
    BuildingAreaTotal: { type: "number" },
    BuildingAreaSource: { type: "string", maxLength: 50 },
    BuildingAreaUnits: { type: "string", maxLength: 25 },
    CommonWalls: { type: "string", maxLength: 1024 },
    PropertyAttachedYN: { type: "boolean" },
    FoundationArea: { type: "number" },
    GarageYN: { type: "boolean" },
    GarageSpaces: { type: "number" },
    AttachedGarageYN: { type: "boolean" },
    CarportSpaces: { type: "number" },
    CarportYN: { type: "boolean" },
    OpenParkingYN: { type: "boolean" },
    OpenParkingSpaces: { type: "number" },
    CoveredSpaces: { type: "number" },
    ParkingFeatures: { type: "string", maxLength: 1024 },
    OtherParking: { type: "string", maxLength: 1024 },
    ParkingTotal: { type: "number" },
    RVParkingDimensions: { type: "string", maxLength: 50 },
    StoriesTotal: { type: "int" },
    Stories: { type: "int" },
    Levels: { type: "string", maxLength: 1024 },
    EntryLocation: { type: "string", maxLength: 50 },
    EntryLevel: { type: "int" },
    YearBuilt: { type: "int" },
    YearBuiltEffective: { type: "int" },
    YearBuiltDetails: { type: "string", maxLength: 1024 },
    YearBuiltSource: { type: "string", maxLength: 60 },
    NewConstructionYN: { type: "boolean" },
    GreenBuildingVerification: { type: "string", maxLength: 1024 },
    BuilderName: { type: "string", maxLength: 50 },
    BuilderModel: { type: "string", maxLength: 50 },
    Heating: { type: "string", maxLength: 1024 },
    HeatingYN: { type: "boolean" },
    Cooling: { type: "string", maxLength: 1024 },
    CoolingYN: { type: "boolean" },
    InteriorFeatures: { type: "string", maxLength: 1024 },
    ExteriorFeatures: { type: "string", maxLength: 1024 },
    PatioAndPorchFeatures: { type: "string", maxLength: 1024 },
    ArchitecturalStyle: { type: "string", maxLength: 1024 },
    FireplaceFeatures: { type: "string", maxLength: 1024 },
    FireplacesTotal: { type: "int" },
    FireplaceYN: { type: "boolean" },
    DoorFeatures: { type: "string", maxLength: 1024 },
    WindowFeatures: { type: "string", maxLength: 1024 },
    Roof: { type: "string", maxLength: 1024 },
    ConstructionMaterials: { type: "string", maxLength: 1024 },
    FoundationDetails: { type: "string", maxLength: 1024 },
    Basement: { type: "string", maxLength: 1024 },
    Flooring: { type: "string", maxLength: 1024 },
    OtherStructures: { type: "string", maxLength: 1024 },
    DirectionFaces: { type: "string", maxLength: 25 },
    OtherEquipment: { type: "string", maxLength: 1024 },
    Appliances: { type: "string", maxLength: 1024 },
    LaundryFeatures: { type: "string", maxLength: 1024 },
    SecurityFeatures: { type: "string", maxLength: 1024 },
    NumberOfSeparateElectricMeters: { type: "int" },
    NumberOfSeparateGasMeters: { type: "int" },
    NumberOfSeparateWaterMeters: { type: "int" },
    GreenEnergyEfficient: { type: "string", maxLength: 1024 },
    GreenEnergyGeneration: { type: "string", maxLength: 1024 },
    GreenSustainability: { type: "string", maxLength: 1024 },
    GreenWaterConservation: { type: "string", maxLength: 1024 },
    GreenIndoorAirQuality: { type: "string", maxLength: 1024 },
    GreenLocation: { type: "string", maxLength: 1024 },
    WalkScore: { type: "int" },
    HabitableResidenceYN: { type: "boolean" },
    MobileLength: { type: "int" },
    MobileWidth: { type: "int" },
    BodyType: { type: "string", maxLength: 1024 },
    Skirt: { type: "string", maxLength: 1024 },
    MobileDimUnits: { type: "string", maxLength: 25 },
    ParkName: { type: "string", maxLength: 50 },
    ParkManagerName: { type: "string", maxLength: 50 },
    ParkManagerPhone: { type: "string", maxLength: 16 },
    MobileHomeRemainsYN: { type: "boolean" },
    Make: { type: "string", maxLength: 50 },
    Model: { type: "string", maxLength: 50 },
    NumberOfPads: { type: "int" },
    SerialU: { type: "string", maxLength: 25 },
    DOH1: { type: "string", maxLength: 25 },
    License1: { type: "string", maxLength: 25 },
    SerialX: { type: "string", maxLength: 25 },
    DOH2: { type: "string", maxLength: 25 },
    License2: { type: "string", maxLength: 25 },
    SerialXX: { type: "string", maxLength: 25 },
    DOH3: { type: "string", maxLength: 25 },
    License3: { type: "string", maxLength: 25 },
    AccessibilityFeatures: { type: "string", maxLength: 1024 },
    RoomsTotal: { type: "int" },
    RoomType: { type: "string", maxLength: 1024 },
    UnitType: { type: "string", maxLength: 1024 },
    Zoning: { type: "string", maxLength: 25 },
    ZoningDescription: { type: "string", maxLength: 255 },
    ParcelNumber: { type: "string", maxLength: 50 },
    AdditionalParcelsYN: { type: "boolean" },
    AdditionalParcelsDescription: { type: "string", maxLength: 255 },
    TaxLot: { type: "string", maxLength: 25 },
    TaxBlock: { type: "string", maxLength: 25 },
    TaxTract: { type: "string", maxLength: 25 },
    TaxLegalDescription: { type: "string", maxLength: 6000 },
    TaxAmount: { type: "int" },
    TaxAmountFrequency: { type: "string", maxLength: 25 },
    TaxYear: { type: "int" },
    TaxAssessedValue: { type: "int" },
    TaxExemptions: { type: "string", maxLength: 1024 },
    TaxOtherAssessmentAmount: { type: "int" },
    TaxOtherAssessmentAmountFrequency: { type: "string", maxLength: 25 },
    TaxBookNumber: { type: "string", maxLength: 25 },
    TaxMapNumber: { type: "string", maxLength: 25 },
    TaxParcelLetter: { type: "string", maxLength: 25 },
    TaxStatusCurrent: { type: "string", maxLength: 50 },
    PublicSurveySection: { type: "string", maxLength: 20 },
    PublicSurveyTownship: { type: "string", maxLength: 20 },
    PublicSurveyRange: { type: "string", maxLength: 20 }
});

$data.Entity.extend("Members", {
    JobTitle: { type: "string", maxLength: 50 },
    MemberAddress1: { type: "string", maxLength: 50 },
    MemberAddress2: { type: "string", maxLength: 50 },
    MemberAOR: { type: "string", maxLength: 50 },
    MemberAORkey: { type: "string", maxLength: 255 },
    MemberAORMlsId: { type: "string", maxLength: 25 },
    MemberCarrierRoute: { type: "string", maxLength: 9 },
    MemberCity: { type: "string", maxLength: 50 },
    MemberCountry: { type: "string", maxLength: 2 },
    MemberCountyOrParish: { type: "string", maxLength: 50 },
    MemberDesignation: { type: "string", maxLength: 50 },
    MemberDirectPhone: { type: "string", maxLength: 16 },
    MemberEmail: { type: "string", maxLength: 80 },
    MemberFax: { type: "string", maxLength: 16 },
    MemberFirstName: { type: "string", maxLength: 50 },
    MemberFullName: { type: "string", maxLength: 150 },
    MemberHomePhone: { type: "string", maxLength: 16 },
    MemberKey: { type: "string", maxLength: 255 },
    MemberLastName: { type: "string", maxLength: 50 },
    MemberLoginId: { type: "string", maxLength: 25 },
    MemberMiddleName: { type: "string", maxLength: 50 },
    MemberMlsId: { type: "int", key: true, computed: false},
    MemberMobilePhone: { type: "string", maxLength: 16 },
    MemberNamePrefix: { type: "string", maxLength: 10 },
    MemberNameSuffix: { type: "string", maxLength: 10 },
    MemberNickname: { type: "string", maxLength: 50 },
    MemberNrdsID: { type: "string", maxLength: 25 },
    MemberOfficePhone: { type: "string", maxLength: 16 },
    MemberOfficePhoneExt: { type: "int" },
    MemberPager: { type: "string", maxLength: 16 },
    MemberPassword: { type: "string", maxLength: 25 },
    MemberPhoneTTYTDD: { type: "string", maxLength: 16 },
    MemberPostalCode: { type: "string", maxLength: 10 },
    MemberPostalCodePlus4: { type: "string", maxLength: 4 },
    MemberPreferredPhone: { type: "string", maxLength: 16 },
    MemberPreferredPhoneExt: { type: "int" },
    MemberTollFreePhone: { type: "string", maxLength: 16 },
    MemberVoiceMail: { type: "string", maxLength: 16 },
    MemberVoiceMailExt: { type: "int" },
    MemberStateLicense: { type: "string", maxLength: 50 },
    MemberStateLicenseState: { type: "string", maxLength: 2 },
    MemberStateOrProvince: { type: "string", maxLength: 2 },
    MemberMlsAccess: { type: "boolean" },
    MemberStatus: { type: "string", maxLength: 25 },
    MemberMlsSecurityClass: { type: "string", maxLength: 25 },
    MemberType: { type: "string", maxLength: 25 },
    MemberAssociationComments: { type: "string", maxLength: 500 },
    MemberLanguages: { type: "string", maxLength: 1024 },
    OfficeKey: { type: "string", maxLength: 255 },
    OfficeMlsId: { type: "int"},
    OfficeName: { type: "string", maxLength: 50 },
    OriginatingSystemMemberKey: { type: "string", maxLength: 255 },
    OriginatingSystemName: { type: "string", maxLength: 255 },
    TimestampEntered: { type: "datetime" },
    TimestampLastLoggedIn: { type: "datetime" },
    TimestampModified: { type: "datetime" }
});

$data.Entity.extend("Media", {
    MediaKey: { type: "string", key: true, computed: false },
    ResourceRecordKey: { type: "string" },
    ResourceRecordID: { type: "string" },
    OriginatingSystemMediaKey: { type: "string" },
    OriginatingSystemName: { type: "string" },
    ObjectID: { type: "string" },
    ChangedByMemberMlsID: { type: "string" },
    ChangedByMemberKey: { type: "string" },
    MediaCategory: { type: "string" },
    MimeType: { type: "string" },
    ShortDescription: { type: "string" },
    LongDescription: { type: "string" },
    ModificationTimestamp: { type: "string" },
    MediaModificationTimestamp: { type: "string" },
    MediaURL: { type: "string" },
    ObjectHTML: { type: "string" },
    Order: { type: "string" },
    Group: { type: "string" },
    ImageWidth: { type: "string" },
    ImageHeight: { type: "string" },
    ImageSizeDescription: { type: "string" },
    ClassName: { type: "string" },
    ResourceName: { type: "string" },
    Permission: { type: "string" },
    MediaStatus: { type: "string" }
});

$data.Entity.extend("Offices", {
    OfficeKey: { type: "string" },
    OriginatingSystemOfficeKey: { type: "string" },
    OriginatingSystemName: { type: "string" },
    OfficeMlsId: { type: "string", key: true, computed: false },
    OfficeName: { type: "string" },
    OfficePhone: { type: "string" },
    OfficePhoneExt: { type: "string" },
    OfficeFax: { type: "string" },
    OfficeEmail: { type: "string" },
    OfficeType: { type: "string" },
    OfficeBranchType: { type: "string" },
    OfficeAOR: { type: "string" },
    OfficeAORMlsId: { type: "string" },
    OfficeAORkey: { type: "string" },
    OfficeNrdsId: { type: "string" },
    OfficeCorporateLicense: { type: "string" },
    OfficeBrokerMlsId: { type: "string" },
    OfficeBrokerKey: { type: "string" },
    OfficeManagerMlsId: { type: "string" },
    OfficeManagerKey: { type: "string" },
    OfficeAddress1: { type: "string" },
    OfficeAddress2: { type: "string" },
    OfficeCity: { type: "string" },
    OfficeStateOrProvince: { type: "string" },
    OfficePostalCode: { type: "string" },
    OfficePostalCodePlus4: { type: "string" },
    OfficeCountyOrParish: { type: "string" },
    OfficeStatus: { type: "string" },
    OfficeAssociationComments: { type: "string" },
    TimestampEntered: { type: "string" },
    TimestampLastLoggedIn: { type: "string" },
    TimestampModified: { type: "string" },
    MainOfficeKey: { type: "string" },
    MainOfficeMlsId: { type: "string" },
    FranchiseAffiliation: { type: "string" },
    IDXOfficeParticipationYN: { type: "string" }
});

$data.Class.defineEx("DatabaseContext", [$data.EntityContext,$data.ServiceBase], null, {
    Properties: { type: $data.EntitySet, elementType: Properties },
    Members: { type: $data.EntitySet, elementType: Members },
    Media: { type: $data.EntitySet, elementType: Media },
    Offices: { type: $data.EntitySet, elementType: Offices }
});

module.exports = exports = DatabaseContext;